### ISSUE TITLE
How do I modify the floating window?

### ISSUE THREAD

**Issue by denstiny** [tjdevries/colorbuddy.nvim#12]
![image](https://user-images.githubusercontent.com/57088952/105640477-4258ab00-5eb9-11eb-9fd1-fd1b10f6ea10.png)
I don't like the black background, could you tell me how
to change into other colors

**Comment by abenz1267** [comment]
There's a typo in most example themes. The group for floating windows is `NormalFloat` and not `NormalFloating`.
