### ISSUE TITLE
Use to override current colorscheme

### ISSUE THREAD

**Issue by likern** [tjdevries/colorbuddy.nvim#13]
Hello @tjdevries! Sorry, if it's a noob question, not very proficient in Lua.

Can I use it to override current colorscheme?
I need to override `OperatorSandwichChange`, ... from [vim-sandwich](https://github.com/machakann/vim-sandwich) to show selection in `vscode-neovim`

![image](https://user-images.githubusercontent.com/842306/107659806-9ffe3d00-6c98-11eb-8e9c-7be6291a3873.png)

```vim
hi OperatorSandwichChange guifg='red' guibg='orange' gui=underline ctermfg='green' cterm=underline
hi OperatorSandwichAdd guifg='green' guibg='orange' gui=underline ctermfg='green' cterm=underline
```

I've come up to this lua snippet. **Can I do this more lua-way with you colorbuddy plugin?**

```lua
local VimSandwichHighlights = function()
    vim.api.nvim_exec([[
      function! MyHighlights() abort
        hi OperatorSandwichChange guifg='red' guibg='orange' gui=underline ctermfg='green' cterm=underline
        hi OperatorSandwichAdd guifg='green' guibg='orange' gui=underline ctermfg='green' cterm=underline
      endfunction

      augroup MyColors
          autocmd!
          autocmd ColorScheme * call MyHighlights()
      augroup END
    ]], false)
end

VimSandwichHighlights()
```

**Comment by likern** [comment]
And, a little outside, but if you could help would be awesome.

How this can be done in pure lua?
```vim
if exists('g:vscode')
    " VSCode extension
else
    " ordinary neovim
endif
```

**Comment by corpooo** [comment]
Any updates on this? I would love to use this plugin to override my colorscheme.

**Comment by tjdevries** [comment]
I will try and implement this soon I think :) haven't looked at this project in awhile

**Comment by corpooo** [comment]
I did open a PR with this. It may not be the best solution, but it works. https://github.com/tjdevries/colorbuddy.nvim/pull/16

**Comment by tjdevries** [comment]
So I actually pushed something pretty similar:

https://github.com/tjdevries/colorbuddy.nvim/issues/7#issuecomment-820712612

Can you try this and see if it does what you're hoping?

**Comment by corpooo** [comment]
When i use `require"colorbuddy".colorscheme` with my colorscheme I get an error saying my theme is not a module.

```
E5113: Error while calling lua chunk: ...ack/packer/start/colorbuddy.nvim/lua/colorbuddy/init.lua:50: module 'snazzy' not found:
        no field package.preload['snazzy']
        no file './snazzy.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/luajit-2.1.0-beta3/snazzy.lua'
        no file '/usr/local/share/lua/5.1/snazzy.lua'
        no file '/usr/local/share/lua/5.1/snazzy/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/lua/5.1/snazzy.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/lua/5.1/snazzy/init.lua'
        no file './snazzy.so'
        no file '/usr/local/lib/lua/5.1/snazzy.so'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/lib/lua/5.1/snazzy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

EDIT: But if I don't use `require"colorbuddy".colorscheme`, my colorscheme is not overwritten by default.

**Comment by tjdevries** [comment]
Oh.... Right. Let me think about that. Maybe I'll add another option so that doesn't fail.

**Comment by chrboesch** [comment]
Same error, nothing has happend since, sad. :-(

**Comment by tjdevries** [comment]
You can try latest master and see if it works for you now. If I'm understand what you want to do:

```lua
require("colorbuddy").colorscheme("name_of_some_other_color_scheme")

-- use colorbuddy down here to do whatever you wanted to do
```

**Comment by chrboesch** [comment]
Now it works, thank you! :-)

**Comment by tjdevries** [comment]
Cool, glad it works :) I made this plugin a long time ago and made a lot of dumb decisions. Maybe someday I will find enough time to fix the dumb decisions :laughing:
