### ISSUE TITLE
Remove globals?

### ISSUE THREAD

**Issue by bbenzikry** [tjdevries/colorbuddy.nvim#18]
Hi @tjdevries, will it be possible to remove the globals definition below? I'm in the process of writing a theme using colorbuddy and my nvim config uses some of the globals (especially the single letter ones. For example, g is vim.g ) 
Seems like this is a common occurrence in similar nvim configurations I've looked at. 

https://github.com/tjdevries/colorbuddy.nvim/blob/cb9e044ebf0b690a56ebb4018cf300703f8dbec1/lua/colorbuddy/init.lua#L34-L47

**Comment by tjdevries** [comment]
Fixed :) I just removed them. It was from a time where I was a lot less of a thinker haha
