### ISSUE TITLE
How to change guisp colors

### ISSUE THREAD

**Issue by marko-cerovac** [tjdevries/colorbuddy.nvim#21]
Hi, I'm configuring my colorscheme to work with built in LSP and I don't know how to set the LspDiagnosticsUnderline variables.
When I set the varable foreground color to red, it changes the entire word to red when there's an error, instead of just the underline.
As far as I know, the foreground color should be left as NONE and the guisp color set to red.
Is there a way to set it using colorbuddy or should I just use vim.cmd ?

**Comment by ofrades** [comment]
I am using something like:
```
local Color, c, Group, g, s = require("colorbuddy").setup()
local ul = s.underline
Group.new("LspDiagnosticsUnderlineError", c.red500, c.none, ul)
Group.new("LspDiagnosticsUnderlineHint", c.green500, c.none, ul)
Group.new("LspDiagnosticsUnderlineInformation", c.blue500, c.none, ul)
```

Hope that helps!

**Comment by marko-cerovac** [comment]
Yeah, I've also been doing that, but then the entire text gets highlighted (at least in my case).
I want the text to remain the same color, but the underline to be red.

**Comment by ofrades** [comment]
the entire text is highlighted probably from the sign_define you have

try removing that to see if it is fixed.

it works well on my side

![image](https://user-images.githubusercontent.com/31070771/115043738-bdd06400-9ecc-11eb-885c-56e81d0c4b87.png)

you can check my [dots](https://github.com/ofrades/configs/blob/aafdc4266c9a4caf3e8a274c73f8c0149d747cb6/.config/nvim/lua/lsp/init.lua#L78)

**Comment by marko-cerovac** [comment]
I've managed to make it work using vim.api.nvim_command (for other people)...
This is what I was aiming for:
![114609819-0d582b00-9c54-11eb-986a-f07267ec0de5](https://user-images.githubusercontent.com/76592799/115050625-3985dd00-9edc-11eb-9552-ea23c81af6c7.png)

Something is wrong with my config, because I'm  getting this:
![114604294-01428c80-9c99-11eb-97d8-f9fa0a5ebebb](https://user-images.githubusercontent.com/76592799/115050725-55897e80-9edc-11eb-86e1-124e1358cd61.png)

(Both screenshots are made using the same colorsheme)

As far as sign_define goes, I'm using lspsaga to provide signs, so I've removed sign_define

**Comment by tjdevries** [comment]
You can now configure guisp colors with the fourth argument for `Group.new(name, fg, bg, style, guisp)` as of 4d57f3af5eb85cbb22fa0cddd457a1e8daca4b73 .

Let me know if that works for you :) you can configure the same was as fg and bg

**Comment by marko-cerovac** [comment]
Thanks man, you're a lifesaver

**Comment by tjdevries** [comment]
When I first created this, I'm not sure if guisp existed or not, but I definitely didn't konw about it :laughing: glad to add new features to this. It's one of my first lua plugins and holds a special place in my heart haha

**Comment by marko-cerovac** [comment]
Thanks again, 
Also, your videos are a big help as I'm learning lua and how to write plugins.😁

**Comment by tjdevries** [comment]
Very glad to hear it :)
