### ISSUE TITLE
Toggling colors throws error

### ISSUE THREAD

**Issue by jc00ke** [tjdevries/colorbuddy.nvim#25]
![image](https://user-images.githubusercontent.com/18191/115789795-8ead6d00-a37a-11eb-8388-683cac3bd8ce.png)

Apologies if this doesn't belong here; I can't quite tell by the error message.

Here's the relevant section of my `init.lua` file:

```lua
paq 'tjdevries/colorbuddy.vim'
paq 'marko-cerovac/material.nvim'
require('colorbuddy').colorscheme('material')
require('material').change_style('oceanic')
map('n', '<leader>L', [[<Cmd>lua require('material').change_style('lighter')<CR>]], { noremap = true, silent = true })
map('n', '<leader>D', [[<Cmd>lua require('material').change_style('oceanic')<CR>]], { noremap = true, silent = true })
```

When I use `<leader>L` or `<leader>D` to switch colors, I get that error message.

I'd be happy to provide more info. I'm on latest commits from each project. Thanks for your help!

**Comment by tjdevries** [comment]
hopefully fixed this now :)
