### ISSUE TITLE
Attempt to index global 'bit' (a nil value)

### ISSUE THREAD

**Issue by mazunki** [tjdevries/colorbuddy.nvim#27]
On a fresh install of Neovim, which uses Lua 5.1 by default, I am getting the following error:

`E5108: Error executing lua ...nvim/plugged/colorbuddy.vim/lua/colorbuddy/color.lua:34: attempt to index global 'bit' (a nil value)`

My `~/.config/nvim/init.vim`:
```vim
call plug#begin(stdpath('data') . '/plugged')
        Plug 'tjdevries/colorbuddy.vim'
        Plug 'tjdevries/gruvbuddy.nvim'
call plug#end()
```

After going a bit back and forth I realized the problem came from the `bit.tohex()` function, which after a bit of research made sense. `bit` is expected to exist as an imported module in a variable, and since it doesn't find it, it complains.

I managed to solve the problem by adding the required module into `~/.local/share/nvim/plugged/colorbuddy.vim/lua/colorbuddy/color.lua`, after `local log = require("colorbuddy.lua")` as `local bit = require("bit")`.

Of course, I had to download [Lua BitOp](http://bitop.luajit.org/download.html), and unzip it into `~/.local/share/nvim/lua/` before it actually could import it as a requirement.

I suggest changing the way this is implemented, either by using Lua v5.3+ bitwise operators (even though, from my end, only Lua 5.1 is built-in with Neovim... which is sad), or including Lua BitOp as a dependency, and adding the import as I did.

**Comment by tjdevries** [comment]
It only took 3 years but i got it

**Comment by mazunki** [comment]
yay!
(i had completely forgot about this)
