### ISSUE TITLE
How to set underline color?

### ISSUE THREAD

**Issue by ogesaku** [tjdevries/colorbuddy.nvim#30]
Hi,

Is there a way to setup underline color?
I would like to achieve sth similar to:
```
highlight SpellBad gui=undercurl guifg=NONE guibg=NONE guisp=#e0af68
```

Regards

**Comment by tjdevries** [comment]
You can set `guisp` with Group.new now

`Group.new = function(name, fg, bg, style, guisp, blend) ... end`
