### ISSUE TITLE
SVG examples in colorbuddy

### ISSUE THREAD

**Issue by ghost** [tjdevries/colorbuddy.nvim#32]
The SVG examples (or screenshots) in the colorbuddy page using a lot of ram(more than 1GB) and the images don't stay loaded and disappear while scrolling. Some other projects use gif, if you can please switch to those.

**Comment by tjdevries** [comment]
which colorbuddy page?

**Comment by tjdevries** [comment]
Ah, nvm, I see what you're saying. I've moved the pictures to the wiki as well
