### ISSUE TITLE
Set highlights WinSeparator guibg=None for laststatus=3

### ISSUE THREAD

**Issue by just1602** [tjdevries/colorbuddy.nvim#35]
Hello!

I was wondering if there would be a way to set `:highlights WinSeparator guibg=None` directly in the theme since you suggest that in the global status line presentation video you did yesterday?

Thanks for all the works in any case! :)

**Comment by kantanahere** [comment]
@just1602 How to add :highlights WinSeperator guibg=None
to neovims init.vim config file, Whats the syntax can you please help ?

**Comment by just1602** [comment]
@athaarvaaagit I have this in my `init.lua`

```lua
vim.cmd [[highlight WinSeparator guibg=None]]
require('colorbuddy').colorscheme('gruvbuddy')
```
