### ISSUE TITLE
Background color not being set

### ISSUE THREAD

**Issue by Wmbat** [tjdevries/colorbuddy.nvim#37]
Hello, I'm writing a colorscheme for my neovim and i set the `Normal` group like so in my theme file: 
```
Group.new('Normal',  colors.fg, colors.bg, styles.NONE)
```
with fg and bg being: 
```
Color.new('fg', #c5cdd9')
Color.new('bg', '#2b2d3a')
```
but, the background color is not correct, while every other color is. This is what the background color is at the moment
![incorrect_bg](https://user-images.githubusercontent.com/25081455/160502838-2162c534-3260-40f7-90dc-417f1be5ca5f.png)
which has the hex value `282c34` instead of `2b2d3a`. Do you have any idea why?

The entire theme is located [here](https://github.com/Wmbat/wmbat-dark/blob/test/lua/wmbat-dark.lua) if needed.

**Comment by k9ur** [comment]
Might need to update the link.
Are you sure image compression is not to blame for this?

**Comment by jesseleite** [comment]
I ran into this too. It seems `bg`, `background`, etc. are reserved words (which seems awkward for a theme helper/framework, where it's probably pretty common for a theme creator to define a `bg` or `background` color).

What are your thoughts @tjdevries, might you be open to a PR to free up these reserved words?

**Comment by tjdevries** [comment]
yes, definitely open to that

**Comment by jesseleite** [comment]
🔥 https://github.com/tjdevries/colorbuddy.nvim/commit/5114e2c9ac9c0a39487c45f848c55f4f5c8517df
