### ISSUE TITLE
Disable plugins

### ISSUE THREAD

**Issue by pwntester** [tjdevries/colorbuddy.nvim#7]
Im expecting colorbuddy to not override vim defaults. For example, my colorscheme does not define `vimCommand` because I want to keep it linked to `Statement`. How can I disable the `languages` plugin?

**Comment by pwntester** [comment]
Actually, it would be nice to disable all default colors and use vim defaults instead

**Comment by pwntester** [comment]
For the time being, Im just calling `hi! clear` before setting my scheme to get rid of all colorbuddy defaults, but I think it would be better to keep vim's defaults and move your colorscheme out to a separate plugin :D

**Comment by rockerBOO** [comment]
Yeah I also agree that no highlights should be set by this plugin. Should be for others to set their own highlights.

**Comment by tjdevries** [comment]
OK, I think this will work now if you do `require('colorbuddy').colorscheme('name', 'dark', { disable_defaults = true })`

**Comment by tjdevries** [comment]
Does it do what you want?

**Comment by pwntester** [comment]
Yep, thanks!
